### ISSUE TITLE
Typoscript not found error due to wrong include names

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [nitsan-technologies/ns_all_lightbox#9]
Hi,

with 5.0.3. the typoscript include name was changed from darkbox to colorbox in these files:

Configuration/TypoScript/setup.typoscript
Configuration/TypoScript/VersionBelow9/setup.typoscript

which leads to log errors:

File "EXT:ns_all_lightbox/Configuration/TypoScript/TYPO3/colorbox.typoscript" was not found. 

Please change back to darkbox. ;-)

**Comment by nitsan-technologies** [comment]
Hello @h-e-l-l-o-w-o-r-l-d 

Thank you for bringing this to our attention and we apologize for the delayed response!

We’re happy to let you know that the issue has already been fixed in the latest version. The TypoScript inclusion name has been updated, and the log errors should no longer occur. Please update to the latest version to resolve this.

If you have any further questions or issues, feel free to reach out.

Thanks again for your feedback and support!

Best regards,
Team NITSAN
